### ISSUE TITLE
First access of /admin not working

### ISSUE THREAD

**Issue by inhahe** [Mr-Kumar-Abhishek/writer-s-desk#2]
I installed it, then tried to navigate to /writer-s-desk/admin, and I get this error: 

Notice: Undefined variable: db in /var/www/html/writer-s-desk/includes/config.php on line 11

Fatal error: Uncaught Error: Call to a member function setAttribute() on null in /var/www/html/writer-s-desk/includes/config.php:11 Stack trace: #0 /var/www/html/writer-s-desk/admin/index.php(3): require_once() #1 {main} thrown in /var/www/html/writer-s-desk/includes/config.php on line 11

Since the error seems to be in config.php, I'll include my config.php up to line 11:

```
<?php
ob_start();
session_start();

//database credentials
define('DBHOST','localhost'); // database name
define('DBUSER','writersdesk'); // database user
define('DBPASS','not my real password'); // database password
define('DBNAME','writer_s_desk'); // database name
define('DBPORT', '8889'); // database port either 8889 or 3306$db = new PDO("my$
$db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
```

**Comment by inhahe** [comment]
Nevermind, I think I accidentally deleted a line from config.php somehow. I re-cloned writersdesk and don't get that error anymore.

**Comment by Mr-Kumar-Abhishek** [comment]
Okay, you might want to look at disqus code too for commenting system and the short code at `viewpost.php` 

```
	<script type='text/javascript'>
			/* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
			var disqus_shortname = 'yourshortcode'; // required: replace example with your forum shortname
				(function() {
					var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
					dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
					(document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
			})();
	</script>

``` 

Just added it recently so I haven't added the documentation yet. Apart from this I am adding new enhancements for SEO such as keywords and meta descriptions for every page. Feel free to add an issue for any enhancements you might want in this. I am going on tour for 15 days so I won't be committing very often on those days. After that I will start with SEO and other enhancements.

**Comment by Mr-Kumar-Abhishek** [comment]
Closing this issue since I didn't find any on problems while checking into my machine. 
Also as you have mentioned earlier you might have deleted this line number 12:

```
$db = new PDO("mysql:host=".DBHOST.";port=".DBPORT.";dbname=".DBNAME, DBUSER, DBPASS);
```
If there are further problems regarding this issue then ask here :smiley_cat: I will re-open it again
